config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :posts

  root 'posts#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ActiveRecord::Base
	validates :image, presence: true

	has_attached_file :image, styles: { :medium => "640x" }
	validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

def index
	@posts = Post.all
end

def new
	@post = Post.new
end

def create
	@post = Post.create(post_params)
	redirect_to posts_path
end

def show
	@post = Post.find(params[:id])
end

def edit
	@post = Post.find(params[:id])
end

def update
	@post = Post.find(params[:id])
	@post.update(post_params)
	redirect_to(posts_path(@post))
end

def destroy
	@post = Post.find(params[:id])
	@post.destroy
	redirect_to posts_path
end

private
	 def post_params
	 	params.require(:post).permit(:image, :caption)
	 end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gunplagram</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/posts">Gunplagram</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="posts/new">New Post</a></li>
        <li><a href="login">Login</a></li>
        <li><a href="register">Register</a></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/edit.html.erb
<div class="posts-wrapper row">
  <div class="post">
    <div class="image center-block">
      <%= image_tag @post.image.url(:medium) %>
    </div>
  </div>
</div>
<div class="form-wrapper">
  <%= simple_form_for @post, html: { class: 'form-horizontal', multipart: true } do |f| %>
    <div class="form-group">
      <%= f.input :image %>
    </div>
    <div class="form-group text-center">
      <%= f.input :caption %>
    </div>
    <div class="form-group text-center">
      <%= f.button :submit, class: 'btn-success' %>
    </div>
    <div class="text-center edit-links">
      <%= link_to "Delete Post", post_path(@post), method: :delete, 
      data: { confirm: "Are you sure you want to delete this post?" } %>
      |
      <%= link_to "Cancel", posts_path %>
    </div>
  <% end %>
</div>

app/views/posts/index.html.erb
<div class="posts-wrapper row">
  <% @posts.each do |post| %>
    <div class="post">
      <div class="post-head">
        <div class="name">
          Max Pokropowicz
        </div>
      </div>
      <div class="image center-block">
        <%= link_to (image_tag post.image.url(:medium), class:'imgresponsive'),post_path(post) %>
      </div>
      <p class="caption">
        <%= post.caption %>
      </p>
    </div>
  <% end %>
</div>

app/views/posts/new.html.haml
.form-wrapper
  = simple_form_for @post, html: { class: 'form-horizontal', multipart: true } do |f|
    .form-group
      = f.input :image
    .form-group.text-center
      = f.input :caption
    .form-group.text-center
      = f.button :submit, class: 'btn-success'

app/views/posts/show.html.erb
<div class="posts-wrapper row">
    <div class="post">
      <div class="post-head">
        <div class="name">
          Max Pokropowicz
        </div>
      </div>
      <div class="image center-block">
        <%= image_tag @post.image.url(:medium) %>
      </div>
      <p class="caption">
        <%= @post.caption %>
      </p>
      <div class="text-center edit-links">
        <%= link_to "Go Back", posts_path %>
        |
        <%= link_to "Edit Post", edit_post_path(@post) %>
      </div>
    </div>
</div>